python/django/five-oh/api/urls.py
from django.conf.urls import patterns, url

from .views import (	
	PostsToJSON,
	HubsToJSON,
    )


urlpatterns = patterns('',
    url(r'^posts/$', PostsToJSON.as_view()),
    url(r'^hubs/$', HubsToJSON.as_view()),
)

python/django/five-oh/five-oh/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', include('hubtubapp.urls')),
	# url(r'^admin/', include(admin.site.urls)),
	url(r'^login/$', auth_views.login, {'template_name': 'hubtubapp/login.html'}, name='login'),
	# url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
#	url(r'^hub/', include('hubtubapp.urls')),
)

python/django/five-oh/hubtubapp/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from hubtubapp.views import (	
    HomeView,
    HubCreate,
    HubDelete,
    ViewAHub,
    HubPermission,
    )


urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^hub/create/$', HubCreate.as_view(), name='create'),
    url(r'^hub/(?P<pk>[-_\w]+)/detail/$', ViewAHub.as_view(), name='hubdetail'),
    url(r'^hub/(?P<pk>[-_\w]+)/delete/$', HubDelete.as_view(), name='hubdelete'),
    url(r'^hub/(?P<pk>[-_\w]+)/permission/$', HubPermission.as_view(), name='permission'),
	url(r'^account/', include('registration.urls')),
    url(r'^api/', include('api.urls')),
)

python/django/five-oh/hubtubapp/models.py
from datetime import date

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

from registration.models import User


class Hub(models.Model):
	""" Room object where discussions will take place. """

	class Meta:
		get_latest_by = 'date_created'

	name = models.CharField(max_length=30, unique=True) 
	public = models.BooleanField(default=False)
	secret_key = models.CharField(max_length=50) 
	description = models.TextField(blank=True)
	unread_messages = models.IntegerField(null=True, blank=True)
	members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='users', blank=True, null=True)
	date_created = models.DateField(("Date"), default=date.today)
	archived = models.BooleanField(default=False, blank=True)
	admin = models.ForeignKey(User)

	def __unicode__(self):
		return u"{0}".format(self.name)

	def get_absolute_url(self):
		return reverse('hubdetail', kwargs={'pk': self.pk})


class Post(models.Model):
	""" Posts that will be inside each Hub. """

	class Meta:
		get_latest_by = 'date_created'

	types = (
		("Image", "Image"),
		("Text", "Text"),
		("URL", "URL")
	)
	type_of = models.CharField(max_length=30, choices=types, default="Text")
	message = models.TextField(max_length=200, blank=True, null=True)
	date_created = models.DateField(('Date'), default=date.today)
	created_by = models.ForeignKey(User, default=None)
	hub = models.ForeignKey(Hub)
	image = models.FileField(blank=True, null=True)
	votes = models.IntegerField(default=0)
	archived = models.BooleanField(default=False, blank=True)

	def __unicode__(self):
		if self.message:
			display = self.message
		else: display = "image from {0}".format(self.created_by)
		return u"{0}: {1}".format(self.type_of, display)


class Comment(models.Model):
	""" Comments that will be under each Post. """

	post = models.ForeignKey(Post)
	comment = models.CharField(max_length=200, blank=False)
	created_by = models.ForeignKey(User, default=None)
	date_created = models.DateField(('Date'), default=date.today)

	def __unicode__(self):
		return u"{0}: {1}".format(self.created_by, self.post)

python/django/five-oh/hubtubapp/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import PasswordInput

from .models import Hub, Post


class HubForm(ModelForm):

	secret_key = forms.CharField(required=False, widget=PasswordInput)

	class Meta:

		model = Hub
		fields = ['name', 'public', 'secret_key', 'description']


class PostForm(ModelForm):

	class Meta:

		model = Post
		fields = ['message']
		labels = {
			'message': 'Contribute to Conversation'
		}
		widgets = {
            'message': forms.TextInput(
                attrs={'id': 'post-text', 'required': True, 'placeholder': 'Say something...'}
            ),
        }

class SecretKey(forms.Form):

	secret_key = forms.CharField(label='Secret Key', widget=PasswordInput())

python/django/five-oh/hubtubapp/views.py
from django.shortcuts import render_to_response
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy, reverse
from django.core.exceptions import ValidationError
from django.views.generic.edit import FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import (
    View,
    TemplateView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    FormView,
    )

from .models import Hub, Post
from .forms import HubForm, PostForm, SecretKey


class HomeView(View):
  
    template_name = 'hubtubapp/home.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(HomeView, self).dispatch(*args, **kwargs)

    def get(self, request, **kwargs):
        """ Returns all Hub objects that User is a member of. """
        hubs = Hub.objects.all().filter(members=request.user)
        return render_to_response(
            self.template_name, 
            {
            'object_list': hubs, 
            'user': request.user
            })


class HubCreate(CreateView):

    model = Hub
    form_class = HubForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.admin = self.request.user
        return super(HubCreate, self).form_valid(form)


class HubDetail(DetailView):

    model = Hub
    template_name = 'hubtubapp/hub_detail.html'
    new_user = False

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(HubDetail, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        """ If Hub not in User.hub_set() redirect to `HubPermission` """
        self.object = self.get_object()
        if self.object.public == False:
            if self.request.user not in self.object.members.all():
                return HttpResponseRedirect(reverse('permission', kwargs={'pk': self.get_object().id}))
            else:
                context = self.get_context_data(object=self.object)
                return self.render_to_response(context)
        else:
            if self.request.user not in self.object.members.all():
                self.object.members.add(self.request.user)
                self.object.save()
                self.new_user = True
            context = self.get_context_data(object=self.object)
            return self.render_to_response(context)
    
    def get_context_data(self, **kwargs):
        context = super(HubDetail, self).get_context_data(**kwargs)
        context['posts'] = Post.objects.all().filter(hub=self.get_object().id)
        context['form'] = PostForm()
        if self.new_user:
            context['welcome'] = "Welcome {0}, to {1}! We love you!".format(self.request.user.firstname, self.object.name)
        return context


class PostCreate(FormView, SingleObjectMixin):

    model = Hub
    form_class = PostForm
    template_name = "hubtubapp/hub_detail.html"
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PostCreate, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseForbidden()
        self.object = self.get_object() # do I need this line?
        return super(PostCreate, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.hub = self.get_object()
        form.save()
        return super(PostCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('hubdetail', kwargs={'pk': self.object.pk})


class ViewAHub(View):
    """
    Combines `HubDetail` and `PostCreate`
    into a single view.
    """

    def get(self, request, *args, **kwargs):
        view = HubDetail.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostCreate.as_view()
        return view(request, *args, **kwargs)


class HubPermission(FormView, SingleObjectMixin):
    """
    Handles adding/removing Users Hubs.
    Prompts for `secret key`.
    """
    
    model = Hub
    form_class = SecretKey
    template_name = 'hubtubapp/secret_key.html'

    def get_context_data(self, **kwargs):
        context = {}
        context['form'] = self.form_class
        return context        

    def get_success_url(self):
        return reverse('hubdetail', kwargs={'pk': self.get_object().pk})

    def post(self, request, *args, **kwargs):
        """ 
        Secret Key should match that field saved in Model definition. 
        Add Hub to user's Hub Set.
        Save User.
        """
        hub = self.get_object()
        if request.POST['secret_key'] == hub.secret_key:
            self.get_object().members.add(self.request.user)
            self.get_object().save()
            return HttpResponseRedirect(reverse('hubdetail', kwargs={'pk': self.get_object().pk}))
        else:
            raise ValidationError("Secret Key was incorrect", code="Secret Key was incorrect")


class HubUpdate(UpdateView):

    model = Hub
    fields = ['name']

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UpdateView, self).dispatch(*args, **kwargs)


class HubDelete(DeleteView):

    model = Hub
    success_url = reverse_lazy('home')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DeleteView, self).dispatch(*args, **kwargs)

python/django/five-oh/templates/hubtubapp/access_denied.html
{% extends 'base_site.html' %}

{% block content %}
<p>Permission Denied</p>
{% endblock %}

python/django/five-oh/templates/hubtubapp/home.html
{% extends 'base_site.html' %}
{% block extra_head %}
<style>
	footer {
		position: fixed; 
		bottom: 0;
	}
	h1{
		font-family: Gill Sans Extrabold, sans-serif !important;
	}
</style>
{% endblock %}
{% block content %}
<h1>Hubs {{ user.firstname }} is a member of:</h1>
{% for key in object_list %}
	<ul class="ui-bar ui-bar-a" id="each_hub">
		<li>
			<a href="{% url 'hubdetail' key.id %}" class="hub_name_home">{{ key.name }}</a>
			<p>Description:<br>"{{ key.description }}"</p>
			<a href="{% url 'hubdelete' key.id %}" class="ui-btn ui-btn-inline">Delete</a>
		</li>
		<li class="home_right">
			<button class="ui-btn ui-btn-inline up-btn"><span class="fa fa-chevron-circle-up"></span></button>
			<div class="well">
				<h4>Other members:</h4>
				{% for i in key.members.all %}
					{% if i.username != user.username %}
						<p>{{ i.username }}</p>
					{% endif %}
				{% endfor %}
			</div>
		</li>
	</ul>
{% endfor %}
{% endblock %}
{% block js %}
<script type="text/javascript">
$(".up-btn").click(function(){

});
</script>
{% endblock %}

python/django/five-oh/templates/hubtubapp/hub_confirm_delete.html
{% extends 'base_site.html' %}

{% block content %}
<p>Are you sure you want to delete </p>{{ object.name }}
<form method="POST">
	{% csrf_token %}
	<input type="submit" value="I want to delete this Hub!"><br>
	<a href="{% url 'home' %}"><button>No take me home.</button></a>
</form>
{% endblock %}

python/django/five-oh/templates/hubtubapp/hub_detail.html
{% extends 'base_site.html' %}

{% block extra_head %}

{% endblock %}

{% block content %}
	{% if welcome %}
	{{ welcome }}
	{% else %}
	<h2>Welcome back! <strong>{{ object.name }}</strong> is lonely without you!</h2>
	{% endif %}
	<div class="ui-bar ui-bar-a ui-corner-all">
		<p>Admin: {{ object.admin }}</p>
		<p>Created On: {{ object.date_created }}</p>
		<p>Description: {{ object.description }}</p>	
	</div>
	<br />
	<div class="posts-container">	
		{% if not posts %}
		<p>There are no posts yet. Create one below!</p>
		{% else %}
			{% for post in posts %}
				<div class="post-container">
					<div class="message">{{ post.message }}</div>
					<div class="poster">- {{ post.created_by }}</div>
					<div class="flex">
						<form class="comment-on-post">
							<input type="text">
						</form>
					</div>
				</div>
			{% endfor %}
		{% endif %}
		<form action="" method="POST" id="post_form">{% csrf_token %}
			{{ form.as_p }}
			<button onclick="create_post()">Send</button>
		</form>
	</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
function create_post(){
	console.log("create_post");
	console.log($('#post-text').val());
	$.ajax({
		url: '/hub/create_post',
		type: 'POST',
		data: {message: $('#post-text').val()}
		success: function(json){
			$('#post-text').val('');
			console.log(json);
			console.log("success");
		},
		error : function(xhr, errmsg, err){
        $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
            " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
        console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
    	},
	});
};
</script>
{% endblock %}

python/django/five-oh/templates/hubtubapp/hub_form.html
{% extends 'base_site.html' %}

{% block content %}
<h1>New Hubs == New Worlds</h1>
<p>Hubs are a great way to keep in touch with others.</p>
<p>You can create one here and send the generated URL to a friend.</p>
<p>Keep in mind, unless you check the option to make your Hub public, your friend will need the "secret key" inorder to fully access the Hub.</p>
<form action="" method="POST">
{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" id="validate_hub" value="Create">
</form>
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function(){
	$("#id_public").click(function(){
		$("#id_secret_key").toggle();
		$("label[for='id_secret_key']").toggle()
	});
});
</script>
{% endblock %}

python/django/five-oh/templates/hubtubapp/login.html
{% extends 'base_site.html' %}

{% block content %}
{{ form.non_field_errors }}
{% if message %}
{{ message }}
{% endif %}
<form method="post" action="">{% csrf_token %}
	<table>
		<tr>
			<td>{{ form.username.label_tag }}</td>
			<td>{{ form.username }}</td>
		</tr>
		<tr>
			<td>{{ form.password.label_tag }}</td>
			<td>{{ form.password }}</td>
		</tr>
	</table>
	<input type="submit" value="login" class="login"/>
</form>

<h3>If you don't have an account create one <a href="{% url 'register' %}">here</a>.</h3>
{% endblock %}

python/django/five-oh/templates/hubtubapp/register.html
{% extends 'base_site.html' %}

{% block content %}

	<h1 class="rotate register_legend">Join the Fun</h1>
	<form action="" method="POST" class="register_form">{% csrf_token %}
		{{ form.as_p }}
		<input type='submit' value='Create My Account'>
	</form>
		
{% endblock %}

python/django/five-oh/templates/hubtubapp/secret_key.html
{% extends 'base_site.html' %}

{% block content %}
{{ form.non_field_errors }}
<form action="" method="POST">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock %}